server:
  port: 
  error:
    include-message: 
spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: 
  security:
    user:
      name: 
      password: 
  jpa:
    hibernate:
      ddl-auto: 
    show-sql: 
    properties:
      hibernate:
        format_sql: 
    database: 
    database-platform: 
    
application:
  security:
    jwt:
      secret-key:
      expiration:
      
admin:
  firstname: 
  lastname:  
  email: 
  password: 
